### ISSUE TITLE
/usr/local/lib/libopencv_nonfree.so.2.4.11：对‘cv::ocl::integral(cv::ocl::oclMat const&, cv::ocl::oclMat&)’未定义的引用

### ISSUE THREAD

**Issue by specialshoot** [AaronMR/ROS_Book_Hydro#24]
/usr/local/lib/libopencv_nonfree.so.2.4.11：对‘cv::ocl::integral(cv::ocl::oclMat const&, cv::ocl::oclMat&)’未定义的引用
I installed libopencv_nonfree successful.
After executing "catkin_make",it shows error.

**Comment by specialshoot** [comment]
I found the way to solve this problem.
reference：http://quabr.com/26553659/linking-opencv-nonfree-components-sift-features-and-ocl-specifically
We needed to turn off the CUDA/OpenCL components of opencv. So instead of running Cmake like this:
`cmake -D WITH_CUDA=ON -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr ..`
We should run:
`cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_OPENCL=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..`
The last dot '.' means the direction of OpenCV root direction.

**Comment by ghost** [comment]
i also

**Comment by ghost** [comment]
give your qq?technology communication

**Comment by specialshoot** [comment]
1217343302
