### ISSUE TITLE
problem running "$ roslaunch chapter8_tutorials gazebo_mapping_robot.launch"

### ISSUE THREAD

**Issue by wt70707** [AaronMR/ROS_Book_Hydro#25]
When I try to run the following, the rviz will not show up.

$ roslaunch chapter8_tutorials gazebo_mapping_robot.launch
model:="`rospack find robot1_description`/urdf/robot1_base_04.xacro"

I put a line:

<node pkg="tf" type="static_transform_publisher" name="footprint_2_odm" args="0 0 0 0 0 0 /odom /base_footprint 100"/>

It works, but when I try to move it, there is an arrow moving, not the robot.

**Comment by echotor** [comment]
Hello Could you explain how you solve the problem? I meet the same problem too.
