### ISSUE TITLE
Fails on Hydro because pcl dependency is not updated properly in package.xml

### ISSUE THREAD

**Issue by kgsrc** [AaronMR/ROS_Book_Hydro#5]
In the package.xml, the dependency on pcl should be changed from "pcl" to "libpcl-all-dev"
Basically in chapter4 and chapter6 package.xml files.

Or else, cannot move past 
rosdep install --from-paths src -iy
ERROR: The following pacakges/stacks could not have thier rosdep keys resovled to system dependencies:
chapter4_tutorials: cannot locate rosdep definition for [pcl]
chapter6_tutorials: cannot locate rosdep definition for [pcl]

To fix this, install pcl via apt-get and then update the package.xml to refer to libpcl-all-dev instead of pcl

**Comment by efernandez** [comment]
Hi @kgopalak , could you indicate the version of Ubuntu you're using?

I did a similar fix for indigo, I think it was OK with "pcl" on hydro. I'll cross check and cherry-pick the fix from indigo-devel if needed.

Thanks.

**Comment by efernandez** [comment]
Got fixed in #6 by cherry-picking the fix from indigo-devel.
